server:
  port: 9001

spring:
  application:
    name: user-service
  cloud:
    vault:
      enabled: true
      uri: ${VAULT_URI:http://vault:8200}
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
        backend: secret
        application-name: ${spring.application.name}
  app:
    feature:
      user-registration-enabled: true
    timeout:
      session: 1800

keycloak:
  admin:
    server-url: ${keycloak.server-url:http://localhost:8180}
    realm: ${keycloak.realm}
    client-id: ${keycloak.client-id}
    client-secret: ${LIBROMESH_CLIENT_SECRET}
    username: ${KEYCLOAK_SERVICE_USERNAME}
    password: ${KEYCLOAK_SERVICE_PASSWORD}