server:
  port: 9001

spring:
  application:
    name: user-service
  cloud:
    vault:
      enabled: true
      uri: ${VAULT_URI:http://localhost:8200}  # Updated to match your Vault UI (localhost:8200)
      authentication: TOKEN
      token: ${VAULT_TOKEN}  # Use environment variable for security
      kv:
        enabled: true
        backend: secret  # Matches the Vault backend from the UI
        application-name: ${spring.application.name}  # Dynamically uses the service name
  app:
    feature:
      user-registration-enabled: true
    timeout:
      session: 1800

    keycloak:
      admin:
        server-url: http://localhost:8180  # Ensure this matches Vault
        realm: ${keycloak.realm:libroMesh}
        client-id: ${keycloak.client-id:libroMesh}
        client-secret: ${keycloak.client-secret:libromesh-secret-2024}
        username: ${keycloak.username:service-account-libromesh}
        password: ${keycloak.password:not-used-for-service-account}