server:
  port: 8081
spring:
  application:
    name: user-service
app:
  feature:
    user-registration-enabled: true
  timeout:
    session: 1800

keycloak:
  admin:
    server-url: http://localhost:8180
    realm: libroMesh
    client-id: libroMesh
    client-secret: ${LIBROMESH_CLIENT_SECRET:libromesh-secret-2024}
    # For service account authentication, these are not needed but kept for compatibility
    username: ${KEYCLOAK_SERVICE_USERNAME:service-account-libromesh}
    password: ${KEYCLOAK_SERVICE_PASSWORD:not-used-for-service-account}
